# frozen_string_literal: true

require 'json'

module NostrZap
  module Zap
    # Builds NOSTR zap receipt events (kind 9735) according to NIP-57.
    #
    # A zap receipt is created when an invoice generated by a zap request is paid.
    # It confirms that the lightning payment was received and should be published
    # to the relays specified in the original zap request.
    #
    # @example
    #   builder = NostrZap::Zap::ReceiptBuilder.new(
    #     zap_request_json: '{"kind":9734,...}',
    #     bolt11_invoice: 'lnbc10n1...',
    #     key_pair: key_pair,
    #     paid_at: Time.now
    #   )
    #   event = builder.build    # => NostrZap::Event
    #   relays = builder.relay_urls
    #
    class ReceiptBuilder
      ZAP_RECEIPT_KIND = 9735

      # @param zap_request_json [String] the original zap request JSON
      # @param bolt11_invoice [String] the BOLT-11 invoice string
      # @param key_pair [KeyPair] key pair for signing
      # @param paid_at [Time, Integer, nil] payment timestamp (defaults to now)
      # @param preimage [String, nil] optional payment preimage
      def initialize(zap_request_json:, bolt11_invoice:, key_pair:, paid_at: nil, preimage: nil)
        @zap_request_json = zap_request_json
        @bolt11_invoice = bolt11_invoice
        @key_pair = key_pair
        @paid_at = normalize_timestamp(paid_at)
        @preimage = preimage
        @zap_request = JSON.parse(zap_request_json)
      end

      # Builds and signs the zap receipt event.
      #
      # @return [Event] the signed zap receipt event
      def build
        event = Event.new(
          kind: ZAP_RECEIPT_KIND,
          content: '',
          tags: build_tags,
          created_at: @paid_at,
        )
        event.sign(@key_pair)
        event
      end

      # Returns the relay URLs from the zap request where the receipt should be published.
      #
      # @return [Array<String>]
      def relay_urls
        relays_tag = @zap_request['tags']&.find { |tag| tag[0] == 'relays' }
        return [] unless relays_tag

        relays_tag[1..] || []
      end

    private

      def normalize_timestamp(value)
        case value
        when nil then Time.now.to_i
        when Integer then value
        else value.to_i
        end
      end

      def build_tags
        tags = []

        tags << ['p', recipient_pubkey] if recipient_pubkey
        tags << ['P', sender_pubkey] if sender_pubkey
        tags << ['e', zapped_event_id] if zapped_event_id
        tags << ['a', addressable_event_coord] if addressable_event_coord
        tags << ['k', target_event_kind] if target_event_kind
        tags << ['bolt11', @bolt11_invoice]
        tags << ['description', @zap_request_json]
        tags << ['preimage', @preimage] if @preimage

        tags
      end

      def recipient_pubkey
        find_tag_value('p')
      end

      def sender_pubkey
        @zap_request['pubkey']
      end

      def zapped_event_id
        find_tag_value('e')
      end

      def addressable_event_coord
        find_tag_value('a')
      end

      def target_event_kind
        find_tag_value('k')
      end

      def find_tag_value(tag_name)
        tag = @zap_request['tags']&.find { |t| t[0] == tag_name }
        tag&.dig(1)
      end
    end
  end
end
